### PR TITLE
Add metrics subsystem

### PR DESCRIPTION
**Pull request by weiiwang01**
Instrumenting the Pollen server using the prometheus Go client library, with the aim of enhancing observability by exposing a range of valuable metrics. This integration will enable the Pollen server to be incorporated more seamlessly into the Canonical observability stack.

The metrics subsystem operates on an opt-in basis. This means it will only initialize by setting the `-metrics-port` flag at the command line.

### CODE REVIEW

**Comment by bryceharrington** [comment]
Hi weiiwang01, thanks for proposing these changes.

Before I do a review, a couple favors.  Can you split this into two PRs, one for the snap, the other for the metrics subsystem?  I think that will make the review more tractable for me, as the requirements for each to land will be quite different.

Second, for the metrics changes, for each new function added please add code docs explaining what the function does.  These don't need to be more than a sentence or two but should give a sense of what the purpose of the routine is and what change(s) it performs.  This will be helpful for me in particular since while I know many programming languages, Go is not (yet) one of them so I'll be learning as I process your PR.  :-)

Add to the end of the README a discussion about using prometheus and the new -metrics-port option in practice.  I'd gear it to someone who maybe already knows a bit about prometheus but not much about pollen.

Please also add yourself to the AUTHORS file.  Email address is optional - this is for credit more than responsibility. ;-)

You can also squash the two snap commits since the latter is just a cleanup of the first.

A couple other things I will want to check with the review...  I see this adds some dependencies and so it'll need to be checked that the Debian packaging for those is adequate in the Ubuntu archive; if not then need to figure out actions to resolve that.

Thanks again, and I'll give deeper review on the code itself in the next round ("the next Go-around"?)

**Comment by weiiwang01** [comment]
Hi @bryceharrington, thanks for your insightful advice. I've updated this pull request to exclude the snap part and updated the codebase and README with additional documentation. 

Regarding dependencies, the metrics system just requires one additional package. For Debian, I think it corresponds to [`golang-github-prometheus-client-golang`](https://tracker.debian.org/pkg/golang-github-prometheus-client-golang). However, the version I am currently using may differ slightly.

**Comment by weiiwang01** [comment]
I'd like to also discuss the version number. Originally, the modifications were intended to use exclusively within the Pollen charm, so we didn't feel the need to increase the version number. That's why the snap currently carries the version `4.22-metrics`. Do you think it's time to update the version number?

**Comment by bryceharrington** [comment]
Hi weiiwang01, yes I figure I will do a release and update the version number at some point here.  Ahead of that I want to:  a) review and land both your branches, b) check around for other contributions or fixes worth inclusion, c) general package work, and d) update anything relating to the change of maintainership.
Unless anyone needs a release urgently, b, c, and d are medium-priority for me and probably won't get serious attention until after feature-freeze at the earliest.  a, though, is high priority and I hope to get review feedback to you early next week.

**Comment by weiiwang01** [comment]
Indeed, an idea that comes to mind is to enhance our TLS configuration. The existing [TLS configuration in Pollen](https://github.com/canonical/pollen/blob/341f0709dfbf516ce872676ee4323114f263b42d/pollen.go#L144) is kind obsolete. I would suggest considering something like [the Intermediate setting recommended by Mozilla](https://ssl-config.mozilla.org/#server=go&version=1.14.4&config=intermediate&hsts=false&guideline=5.7). However, the exact TLS version and cipher suites we should implement may depend upon the Ubuntu version we aim to support and the version of curl it is bundled with. By the way, our current deployment is not affected by this issue.

**Comment by bryceharrington** [comment]
The main issue (and the reason I had been holding off landing this pending a more comprehensive review) is the added dependency on Prometheus.  I was concerned since metrics may be a feature not interesting to all users, or one they'd prefer a different software provider, requiring Prometheus to be installed may impact people.  However, after a closer look I think this worry is unfounded, for a few reasons.

First and foremost, Prometheus has a MIR (LP: #1889679) and thus is on track to become the standard default for Ubuntu users.  Second, Pollen is a universe component, which tends to have more leeway about dependencies than packages in main.  Third, Pollen is a pretty lightweight code currently, and IMHO needs some new features to keep it relevant anyway.

Finally, if this does end up becoming an issue for someone, I'd certainly entertain a followup patch to rework Prometheus to be optional or to generalize the metrics dependence.  But that bridge can be crossed when it's arrived at.

Thanks again for this great work, I'll proceed with getting it integrated and landed.

**Review by bryceharrington — APPROVED** [review]

**Comment by weiiwang01** [comment]
> The main issue (and the reason I had been holding off landing this pending a more comprehensive review) is the added dependency on Prometheus. I was concerned since metrics may be a feature not interesting to all users, or one they'd prefer a different software provider, requiring Prometheus to be installed may impact people. However, after a closer look I think this worry is unfounded, for a few reasons.
> 
> First and foremost, Prometheus has a MIR (LP: #1889679) and thus is on track to become the standard default for Ubuntu users. Second, Pollen is a universe component, which tends to have more leeway about dependencies than packages in main. Third, Pollen is a pretty lightweight code currently, and IMHO needs some new features to keep it relevant anyway.
> 
> Finally, if this does end up becoming an issue for someone, I'd certainly entertain a followup patch to rework Prometheus to be optional or to generalize the metrics dependence. But that bridge can be crossed when it's arrived at.
> 
> Thanks again for this great work, I'll proceed with getting it integrated and landed.

I'm glad to hear that it was merged! I also had concerns about introducing Prometheus. In the current version, Prometheus is a dependency of the binary, but it shouldn't be instantiated or present at runtime unless opted in.

**Pull request merged**
